### ISSUE TITLE
Building fails with 'The system cannot find the specified file.'

### ISSUE THREAD

**Issue by Schokobecher** [lvillani/just-install#213] opened 2016-12-18 14:13 UTC
Trying to set-up a working build environment fails for me.

I installed WiX, Python27 and Golang using just-install and then set the `GOPATH` to `C:\GoProjects` (Which I created, including subdirs like `src`, `pkg` and `bin`.

When I run `python build.py` it results in a ` File not found` error
```
C:\Users\Schok\Documents\GitHub\just-install>python build.py
+ go get github.com/kardianos/govendor
+ govendor sync
Traceback (most recent call last):
  File "build.py", line 85, in <module>
    main()
  File "build.py", line 38, in main
    setup()
  File "build.py", line 48, in setup
    call("govendor", "sync")
  File "build.py", line 81, in call
    check_call(args)
  File "C:\Python27\lib\subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden
```

My `go env `looks like this:

> set GOARCH=386
> set GOBIN=
> set GOEXE=.exe
> set GOHOSTARCH=386
> set GOHOSTOS=windows
> set GOOS=windows
> set GOPATH=C:\GoProjects
> set GORACE=
> set GOROOT=C:\Go
> set GOTOOLDIR=C:\Go\pkg\tool\windows_386
> set CC=gcc
> set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
> set CXX=g++
> set CGO_ENABLED=1

Any suggetions?

**Comment by lvillani** [comment] 2016-12-18 19:03
Is `$GOPATH\bin` in your `$PATH`? It seems the script cannot find `govendor.exe` anywhere.

**Comment by Schokobecher** [comment] 2016-12-18 22:06
Setting that helped a bit, I also had to move the just-install folder into `GOPATH/src`.
After some trouble I got it to almost build completely (qtbittorent has VersionCode 0, Flashplayer 20 is not available anymore, current one is 24). It builds the .exe fine but ends in this error:

> C:\GoProjects\src\github.com\lvillani\just-install>python build.py
> + go get github.com/kardianos/govendor
> + govendor sync
> + go build -o just-install.exe -ldflags -X main.version=v3.2.0-26-g62a2b23
>  ./bin
> + candle just-install.wxs
> Traceback (most recent call last):
>   File "build.py", line 85, in <module>
>     main()
>   File "build.py", line 43, in main
>     build_msi()
>   File "build.py", line 75, in build_msi
>     call("candle", "just-install.wxs")
>   File "build.py", line 81, in call
>     check_call(args)
>   File "C:\Python27\lib\subprocess.py", line 536, in check_call
>     retcode = call(*popenargs, **kwargs)
>   File "C:\Python27\lib\subprocess.py", line 523, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "C:\Python27\lib\subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden 

Sorry for any inconvience that I'm causing :-(

**Comment by geek1011** [comment] 2016-12-18 22:32
I have had this issue when I built just-install. The problem is that the wix binaries are not in your path. The easiest way to fix this is:

1. Uninstall wix
2. just-install exeproxy
3. just-install wix
4. Try again

**Comment by lvillani** [comment] 2016-12-19 19:03
@Schokobecher no problem! @geek1011 procedure is totally spot-on. When you install `exeproxy`, just-install automatically creates a directory (`C:\Shims`) in which it places relevant "wrappers" to  binaries, this way you only have to add a single directory to the `$PATH`. This feature is a little bit under-documented, my bad 😅

**Comment by geek1011** [comment] 2016-12-19 21:15
I can add it to the documentation. I just wanted to make sure it solves the problem first.

**Comment by Schokobecher** [comment] 2016-12-20 22:02
Thanks @geek1011 and @lvillani :dancing_men: 
Everything works now.

**Comment by lvillani** [comment] 2016-12-21 08:12
Glad to hear it! I'm closing this issue for now.

**Closed by lvillani** 2016-12-21 08:12 UTC
